### ISSUE TITLE
BLOCKing bug: Image can't build anymore

### ISSUE THREAD

**Issue by rafabene** [ryanj/origin-s2i-nodejs#16]
After #15 now everyone is facing the following issue:

> npm ERR! Error: EACCES: permission denied, mkdir '/opt/app-root/src/node_modules/.staging'
> npm ERR!     at Error (native)
> npm ERR!  { Error: EACCES: permission denied, mkdir '/opt/app-root/src/node_modules/.staging'
> npm ERR!     at Error (native)
> npm ERR!   errno: -13,
> npm ERR!   code: 'EACCES',
> npm ERR!   syscall: 'mkdir',
> npm ERR!   path: '/opt/app-root/src/node_modules/.staging' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator

Workaround: User has to remove the node_modules/ folder.

**Comment by ryanj** [comment]
crap, will take a look - thx

**Comment by ryanj** [comment]
I reverted the change and pushed some new images. please retest
